# Setup
title: CuteWisp
tagline: ""
description: "CuteWisp"
url: "https://blog.cutewisp.com"
baseurl: ""
paginate: 5
permalink: pretty
future: true

# About/contact
author:
  name: CuteWisp
  url: cutewisp.com
  email: x@cutewisp.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
