# Setup
title:               CuteWisp
tagline:             'A Jekyll theme'
description:         'CuteWisp'
url:                 http://blog.cutewisp.com/
baseurl:             'http://blog.cutewisp.com/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              CuteWisp
  url:               cutewisp.com
  email:             sweatpotato13@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
